### ISSUE TITLE
variable non remplacée dans une chaîne

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#100]
Ce texte est apparu tel-quel:

src/rotp/lang/fr/labels.txt:TECH_DERELICT_TITLE               | Les explorateurs [alien_race_pluraladjec] pillent une technologie ancienne

Les Sakkra ont bien cette variable:
   _race_pluraladjec                 | Ssslauriens, Reptariens, Sauriens, Raptoriens, Tyranniens

**Comment by BrokenRegistry** [comment]
Was a bad translation
Should have been [player_race_pluraladjec]
Fixed
