### ISSUE TITLE
INVASION_LOSS not being displayed

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#101]
This message (and possibly INVASION_WIN) is displayed after the player needs to click to go to the next invasion screen. As such it flashes on screen for a fraction of one second.

INVASION_LOSS                     | Des troupes [defender_race_pluraladjecF] ont réussi à défendre %2.

**Comment by BrokenRegistry** [comment]
This bug was so old that it could almost be considered a feature...
Fixed.
