### ISSUE TITLE
swap SETTINGS_MOD_SCRAP_REFUND and SETTINGS_MOD_SCRAP_REFUND_FACTOR

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#103]
In the options settings, SETTINGS_MOD_SCRAP_REFUND should be first, followed by SETTINGS_MOD_SCRAP_REFUND_FACTOR, since FACTOR depends on the other.

**Comment by BrokenRegistry** [comment]
Fixed
