### ISSUE TITLE
Empty race file: RACE_HUMAN.race

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#109]
I now get these errors / logs:

    ==================== reset all options() ====================
    File not found: ...../remnants-of-precursors/RACE_HUMAN.race
    ==================== loadStartupOptions() ====================
    Empty race file: RACE_HUMAN.race
    Empty race file: RACE_HUMAN.race
    Empty race file: RACE_HUMAN.race
    Empty race file: RACE_HUMAN.race
    Empty race file: RACE_HUMAN.race
    Empty race file: RACE_HUMAN.race

This file exists, but I didn't create it. If I delete it, it comes back.

**Comment by BrokenRegistry** [comment]
Fixed.
You can delete this file.
I did not see this initialisation issue, because I have a valid RACE_HUMAN.race file in my folder...
