### ISSUE TITLE
Empty race file: .race

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#111]
Not human anymore.

    ==================== loadStartupOptions() ====================
    Empty race file: .race
    Empty race file: .race
    Empty race file: .race
    Empty race file: .race
    Empty race file: .race
    Empty race file: .race

**Comment by frank-zago** [comment]
There is a .race file.

**Comment by BrokenRegistry** [comment]
This happen when you don't give a name to a custom species and save it, or set it as player species. "Empty" names are valid name.
Should I add a blocking popup when no name are given to a custom species?

**Comment by frank-zago** [comment]
I don't play with custome species. This is also a fairly new error.

**Comment by BrokenRegistry** [comment]
Found a bug that could lead to this. When choosing a prefered ship set from the pop up, closing this pop up was clearing all the other fields!!! (scrolling was ok)
So, when this species was saved it would get an empty name.
--> Fixed
The fix also makes the "Displayed Species" and "Original" multi-lingual compatible... (They were hard coded.)
