### ISSUE TITLE
technology status in galaxy map is not refreshed when turn starts

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#112]
I have to go to the Tech panel and leave it for the percentages to be set correctly.

**Comment by frank-zago** [comment]
It's possibly because some research just completed and the values were not refreshed then.

**Comment by BrokenRegistry** [comment]
Just adjusting the tech spend (and making it the same value again) was enough to update it...
Well, now it will refresh every time you access the map.
Oddly enough, I thought you were talking about the empire status panel, which wasn't exactly up to date either.
Fixed that too.
