### ISSUE TITLE
message ordering when new planet is discovered

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#118]
If armed ships are sent to an unknown enemy planet, the first message is asking to bombard it and the second will be that a new planet was explored. IMO these 2 messages should be reversed.

**Comment by BrokenRegistry** [comment]
The military being what they are, they tend to let the guns speak first...
But from now on, they will have to send you their reports first.
Fixed

**Comment by BrokenRegistry** [comment]
Removed to fixe wrongly given Orion Tech.

**Comment by BrokenRegistry** [comment]
Fixed, and validated that you don't get free Orion tech!
