### ISSUE TITLE
variable non substituée

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#120]
Dans COUNCIL_CONVENE2 ("Un candidat doit recueillir au moins %1 % de tous"), le %1 n'est pas remplacé.
COUNCIL_CONVENE2_MOD et COUNCIL_CONVENE2 semblent avoir été inversés.

**Comment by BrokenRegistry** [comment]
Bien vu! C'était un copier , coller, suivi de la modification de l'original au lieu de la copie...
Corrigé
