### ISSUE TITLE
incorrect number of factories after bio attack

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#121]
When a planet population gets wiped out by a bio attack (death spores for instance), the attack summary says 0 factories left. This is not true. Colonizing the planet again shows plenty of factories are still standing.

**Comment by BrokenRegistry** [comment]
Never seen this, as I never had one of my colony wiped out...
Do you have a save that I can replay to track this bug?

**Comment by BrokenRegistry** [comment]
Fixed
