### ISSUE TITLE
sending fleet but no fleet selected

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#124]
A long standing annoying bug I can finally reproduce. It needs 2 planets A & B, each with an orbiting fleet.
 
- select orbiting fleet A
- select planet A
- hover the mouse on fleet B,
- hover the mouse on planet B -> it is possible to send the fleet that was previously selected. Also the message on the planet box is MAIN_FLEET_INVALID_DESTINATION.

**Comment by BrokenRegistry** [comment]
Ouch! Un véritable sac de noeuds...
Ça va prendre un peu de temps pour que je m'y retrouve, et que la correction ne se transforme pas en explosion de bugs.

**Comment by BrokenRegistry** [comment]
Fixed this very old bug! (Was almost a feature)
