### ISSUE TITLE
Skip scouting Orion star

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#22]
Version: Fusion-2023-12-24

Background:
Orion star with a Guardian ship near to the home star. Early stage of the game.

Governor Toogle > Options > Fleet Options > Auto Scout is On

What is wrong?
AI/Governor keeps sending ships to early discovered Orion star. 

What is expected?
Send scout or fleet only once. Skip it when well protected star is manually located by Scout ship.

**Comment by BrokenRegistry** [comment]
I'm not able to reproduce: First scout tags the planet has having a monster, then no more scouting!
Do you have a save showing the issue?

**Comment by nhlpl** [comment]
Sorry, no save games as I'm not a gamer. More like MOO fan. Closing.

Will be back if issues occurs. Thanks.
