### ISSUE TITLE
Tactic for a lot of unarmed small ships

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#23]
Version: Fusion-2023-12-24

Background:
MoO1 was well known for small-size ship fleets - huge in numbers. They were hard to beat. Some users may want to test ROTP against such strategy.

Issue:
AI not using unarmed scouts when there a lot of them. Let say 300 or 500.

What is expected:
AI to use such unarmed small ships to block missiles and try to take hits with other weapons.

**Comment by BrokenRegistry** [comment]
Missiles always find their way around untargeted ships. (In MOO1 too)
Ships can not be used as shield! (Neither in MOO1)
AI can't do anything with unarmed ships, because smart players won't spend their missiles on unarmed ships.
