### ISSUE TITLE
Heavy damages and auto-repair

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#24]
Version: Fusion-2023-12-24

Background:
Some level of unrepairable damage level would be nice.

Issue:
Heavy damaged ships repaired next turn. Including those with just few points left to be destroyed.

What is expected?
Heavy damaged ships to slow down fleet or needs to be scraped. Maybe even stop using their weapons during battle when canons or whatever are nonexistent because of taken enemy fire.

**Comment by BrokenRegistry** [comment]
This is not compatible with the current fleet stack combat action, will require AI combat and ship design adjusment: Out of scope.
