### ISSUE TITLE
Fleet destination paths visibility

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#25]
Version: Fusion-2023-12-24

Background:
Zoomed galaxy map and ships going from one end of map to the other end.

Issue:
Destination path invisible for a fleet with a distant world selected as flight target - when you move map to no longer see fleet icon but to check destination star.

What is expected:
An option to always show own fleet journey path and do not auto-hide them (which is really nice feature by the way). Some kind of better visibility for enemy ground troop transports would be also nice to take under consideration.

**Comment by BrokenRegistry** [comment]
An option already exists: "In-Game Option" -> "Shared Options Menu" -> "Zoom Fleet Factors".
The larger the factor, the farthest you will see fleets, paths, and flags.
For enemy ground troop transports visibility:
F7/F8 : Next/Previous player colony with incoming armed enemy fleets or transports
