### ISSUE TITLE
Disabling auto save/backup

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#26]
Version: Fusion-2023-12-24

Background:
Settings > Backup: Off
/backup folder checked for auto-saves

Issue:
Backup writes on every single end turn action.

What is expected:
Disabling backup to take action without a need to close game and start it again.

**Comment by BrokenRegistry** [comment]
Game -> Settings -> Backup: Off -> Exit -> Continue Game => No need to reload a file, the game is still in memory!
Next Turn => No new backup!

Continue Game load a file only when no game is in memory.
Options are still written/read -> disk noise!
