### ISSUE TITLE
AI-Type descriptions

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#27]
Version: Fusion-2023-12-24

Some players may be lost when it comes to choose AI-Type before starting game.

Tips or some kind of helpers based on this comment would be nice to see:
https://www.reddit.com/r/rotp/comments/18h3fqf/comment/kd5vric/
(which one is original by Ray, why choose Character  and what is ignored)

At this moment most people will try to select favorite AI-Type by experience - playing with all of them step by step or with autoplay like me.

**Comment by BrokenRegistry** [comment]
Place the cursor on the AI box and press "G" (for Guide), a pop-up will appear with a short description of the selected AI, scroll the mouse to go thru all AI.
Or press "F1" To get all the descriptions in the the same window.
