### ISSUE TITLE
Selectable default Governor action for new colonies

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#28]
Version: Fusion-2023-12-24

Issue:
Governor selects building industry for newly established colonies with starting population (2).

What is expected:
Governor to give chance to grow population instead of waiting for +0.4 for industry/factories. Some kind of follow action by Governor of what likes/dislikes end user may be useful here.

Thank you.

**Comment by BrokenRegistry** [comment]
Two options already exist for this purpose:
- Develop colonies as quickly as possible.
- Let AI handle population transportation.
If you don't want the factory building: Toggle the colony Governor off, and maximize the ECO. A pop-up will tell you when the colony is fully populated. You can then reactivate the Governor.
