### ISSUE TITLE
Hit space to find idle fleets

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#29]
Version: Fusion-2023-12-24

Issue:
No one knows how to jump between fleets.

What is expected:
One more great tip by Xilmi:
https://www.reddit.com/r/rotp/comments/18rc7hw/comment/kf0hfhf/

Hit space and it works - jumps between owned fleets. Great. Needs some kind of reminder for end user to tell - such feature already exist.

**Comment by BrokenRegistry** [comment]
Was already shown in the hotkey help...
