### ISSUE TITLE
Tech tree randomizer

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#30]
Many people prefer games with changing tech tree.

A good example can be found here:
https://www.reddit.com/r/4Xgaming/comments/hyeq3e/comment/fzcl4ia/
"One additional positive is that you'll never have the same access to the tech tree twice due to a randomizer effect. This can cause you to sometimes need to play a faction different yo how they stereotypical play."

Sound impossible just like multiplanetary systems but still...

**Comment by BrokenRegistry** [comment]
Truly new technologies would require a major adaptation of AI. This is beyond our scope!
You can get a sub set of this by setting "Tech Trading" = No, and "Tech Stealing" = No.
Tech tree are randomized, and each game will be different.
