### ISSUE TITLE
Difficulty: Easier (75%) vs Easy (90%) vs Normal (100%)

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#31]
Version: Fusion-2023-12-24

Issue:
It was too easy to play and win on Easier (75%) level and is too hard on all more demanding levels (Easy and Normal in my case). On regular basis AI wants peace after war and only few turns later it goes back to war. Map is small or average. AI players from 3 to 10. Most of games (Easy level) ends being at war with 3 empires out of 4.

What is expected:
Only 2 and not 3 out of starting 4 AI players at war with human player at once when Easy (90%) level was set.

**Comment by BrokenRegistry** [comment]
Select "Custom", and adjust the "custom dificulty" in "In-game A" or "In-game Options"
