### ISSUE TITLE
Select Your Empire for new factions

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#33]
Version: Fusion-2023-12-24

Screenshot says it all.

Select Your Empire screen:
![racewind](https://github.com/BrokenRegistry/Rotp-Fusion/assets/11160550/9977ba20-e664-46f2-b6b6-890d4f138e2b)

Extra content needs window resizing or scrolling.

**Comment by BrokenRegistry** [comment]
This can be set in "Settings" -> "10 Species only": No = 3 columns; Yes = 2 columns (+ 1 hidden)
The 6 others species are hidden, but still available for compatibility when loading games or option using them.
This is a feature, not a bug!
