### ISSUE TITLE
Tribute to the AI to accept peace

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#34]
Version: Fusion-2023-12-24

Discussed here:
https://www.reddit.com/r/rotp/comments/pmqknc/comment/hcjyxig/

I still think it makes sense to add such option. You can send aid without a reason (to get better relations between empires) so why not a tribute?

**Comment by BrokenRegistry** [comment]
Not a bug, a feature decided by the wise Mr. Fowler!
