### ISSUE TITLE
MOO style alliances

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#35]
Version: Fusion-2023-12-24

I don't know how it works at this moment but a comment below looks interesting.

Discussed here:
https://www.reddit.com/r/rotp/comments/17zj0fe/comment/ka3kh5e/

Please feel free to close this issue. Thank you.

**Comment by BrokenRegistry** [comment]
This is a MOO4 feature... Not MOO1.
And the comment don't seems to get enthousiasm!
