### ISSUE TITLE
Artifacts + Ultra Rich planet

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#36]
Discussed and confirmed as a bug here:
https://www.reddit.com/r/rotp/comments/1882zb2/artifacts_ultra_rich_planet/

Can anyone confirm this?

**Comment by BrokenRegistry** [comment]
Already fixed!
https://www.reddit.com/r/rotp/comments/1882zb2/comment/kbmohv6/?utm_source=share&utm_medium=web2x&context=3
