### ISSUE TITLE
Custom names for stars and ship designs

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#37]
Please take under consideration a plain text file with a custom names to be used for stars/planets and ship designs naming. 

A simple format like `New Earth %1` (New Earth 1, New Earth 2, New Earth 3) or a user provided list.

`#planets/stars
Alpha
Beta
Gamma
Delta
Epsilon
Zeta
Eta
Theta
Iota
Kappa
Lambda`

`#ship designs
Mu
Nu
Xi
Omicron
Pi
Rho
Sigma
Tau
Upsilon
Phi
Chi
Psi
Omega`

**Comment by BrokenRegistry** [comment]
.jar and .exe are compressed folders accessible with most file archivers (7zip, winrar, etc)
System names already are in editable text files:
Examples:
To change english darlok system names:
- edit rotp/lang/en/races/Darlok.systems.txt
To change english darlok ship names:
- edit rotp/lang/en/races/Darlok.names.txt

A duplicate of these files could be confusing... Do you still feel the need?

**Comment by nhlpl** [comment]
Oh, that's great. Thank you for being so informative.

Thank you. Closing this issue.
