### ISSUE TITLE
Random event vs ground troops transport

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#38]
Version: Fusion-2023-12-24

Two examples.

1)
Troops were in short journey from planet A to a rival planet B. In the middle random event and colony on planet B was lost and transformed to Barren type. No fleet on orbit. Transport lost. It makes game challenging so OK. Both sides lost some population and it was a predictable risk.

2)
Rival Empire is now limited to a capital/homeworld. Game prevents me from sending ground troops and demands scouting star/planet. At the same time spies gives information about population, factories, missile bases, fleet, economy and so on. Fleet keeps trying to advance on orbit and destroy defenders infrastructure. I believe it works as it should but is frustrating at best.

What is expected?
1) Reminder on colonies lost due to enemy ground troops landing and about own troops being lost.
2) I don't remember MOO1 and MOO2 to stop user in that way but true is that did not have sophisticated system to do similar things.

**Comment by BrokenRegistry** [comment]
Thes are features:
You need  Hyperspace Communications to be able to redirect troops.
You need to scout a planet before being allowed to send troops. This is a MOO1 feature.
MOO2 troops works differently... But it's another game!
