### ISSUE TITLE
Trying to escape after being destroyed

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#39]
Version: Fusion-2023-12-24

Not a big issue.

Combat. My fleet vs defender planet plus fleet. They shoot rockets and win. All my ships destroyed.

Issue:
Withdraw animation displayed after last ship being destroyed by a missile. To be precise there was one more type of ship and destroyed a little later.

What is expected?
No animation showing exit allowing ship to return to home base.

Sorry, I don't know if it's worth checking and fixing.

**Comment by BrokenRegistry** [comment]
Yes, result panel always pop-up to early!
This is partially fixed for beam attack!
I'll try to fix it for other weapon the next time I play with combat panels...

**Comment by BrokenRegistry** [comment]
Fixed, default delay is 1500ms, there is already an option to adjust this delay.
