### ISSUE TITLE
No filename offered for save game

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#40]
Version: Fusion-2023-12-24

Sorry, I don't know how to reproduce.

When there is no manual save game and ROTP uses file allowing to continue game **there will be no file name offered** in save game window. Not a problem as you can overwrite some other save.

I think it may be space in file name (Kla kla - Average - Easier.rotp) or game being fully randomized.

**Comment by BrokenRegistry** [comment]
Fixed "Continue" will now initialise empty game name.
