### ISSUE TITLE
Reduce required number of clicks

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#41]
One more proposal to take under consideration.

In ancient times of MOO1 and MOO2 it was possible to hold left click to get keep clicking effect. When I need something to be clicked 30 times I'm not doing it but waiting for pushed arrow-up or arrow-down button to start working as mass move button (let say 100 objects or 500 of them and all values between were easy to get).

Please make it possible to change any kind of adjustable counters with just one click (and waiting for counter to change fast while holding left mouse button) instead of current limited behavior (one step for counter to change +1 or -1 only).

Thank you.

**Comment by BrokenRegistry** [comment]
You can use "scroll" on most of the options, and:
Shift down -> +/- 5 (generally)
Ctrl down ->  +/- 20 (generally)
Shift + Ctrl down ->  +/- 100 (Shift * Ctrl)
These values may differs, the guide pop-up gives the real steps values.
Do you have a specific option not working like that?

**Comment by nhlpl** [comment]
There is no scroll on most of the notebook touchpads and if one exist it usually lacks usability.

Thank you for making things clear. Great game.

Closing.
