### ISSUE TITLE
Auto Updater & memory allocation

### ISSUE THREAD

**Issue by nhlpl** [BrokenRegistry/Rotp-Fusion#42]
Frequent releases are great and it would be even better with an auto update feature.

Might be useful. Someone asked for it here:
https://steamcommunity.com/groups/explorminate/discussions/0/412448158143254081/?l=tchinese&ctp=67#c3090012519531689284

Last page, same thread near to the end:
 "_is there a way to increase memory allocation beyond 3GB_?"
https://steamcommunity.com/groups/explorminate/discussions/0/412448158143254081/?l=tchinese&ctp=72#c3880470363409978457

**Comment by BrokenRegistry** [comment]
> auto update feature.

I agree with Ray Fowler idea of  _"I also like being able to say that ROTP never connects to the internet for any reason"_
And there is no installer... just one file to copy in a folder!


> "is there a way to increase memory allocation beyond 3GB?"

Fusion get 3.5GB.
For the .exe: No!
For the .jar: To start with 4GB and have a max of 6GB
java -jar -Xms4g -Xmx6g rotp-Fusion-2023-12-30-mini.jar

**Comment by BrokenRegistry** [comment]
You can now click on the version to get a link to the newer versions, if there is one (or two), both this and Xilmi repositories are checked for updates
