### ISSUE TITLE
Crash on stargate hover

### ISSUE THREAD

**Issue by mchugh19** [BrokenRegistry/Rotp-Fusion#46]
Seeing a crash after hovering over the stargate icon with the mouse cursor.
<img width="208" alt="stargate icon" src="https://github.com/user-attachments/assets/57de92c0-a6b4-4c14-8670-1dd8f88de5d3">

This displays the following error:
![image](https://github.com/user-attachments/assets/5cc899b9-12ff-41b5-ad7c-de3ccbcb2e10)

**Comment by BrokenRegistry** [comment]
Thanks for reporting this bug, it's always appreciated.
This bug has been fixed in more recent versions of RotP-Fusion (since July 23rd).
An upgrade will then fix the problem. I recommend the latest version.

Broken Registry

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by mchugh19** [comment]
Fantastic! Confirmed, updating to the latest build does fix it. 

Thanks so much for keeping this project alive. Moo1 was a wonderful game, and it's so much better with the quality of life improvments you've all done. Kudos!
