### ISSUE TITLE
Invalid tags in language files

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#49]
I've fixed more tag issues in PR #48 .
But this is not limited to that particular language. For instance:

    [my_race_pluralnoun ]
    [your__race_possessive]
    [tvoja_rasaVoc]
    [Defender_race_plural]
    [Ihre_Rasse_plural]
    [your_nametitle]

It'd be worth it to have a unit test that would check every language file and report unknown/invalid tags.
I'm not a java person, so I can't help here.

**Comment by BrokenRegistry** [comment]
An intensive search for erroneously translated keywords was carried out in each available language. Many errors have been corrected.

**Comment by frank-zago** [comment]
What about this one? : [defender_race_relational_]

**Comment by BrokenRegistry** [comment]
This one was not even loaded, it was orphaned text due to wrongly split lines.
Keywords and their attribution must be on the same line, but some translators split them on multiple lines.
Lot of files have this problem!
Now fixed!
