### ISSUE TITLE
Sometimes strings are not translated although translation exists

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#51]
In the diplomatic audience, I've noticed that ANNOUNCE_TRADE_01, OFFER_JOINT_WAR_01 and OFFER_TRADE_01 are sometimes translated, and sometimes not. It even happens with the same race between 2 different visits.

When the info window show a ship orbiting a foreign occupied planet, this one doesn't get translated: MAIN_BOMBARD_TITLE.

**Comment by BrokenRegistry** [comment]
The problem was orphaned text due to wrongly split lines.
Keywords and their attribution must be on the same line, but some translators split them on multiple lines.

**Comment by frank-zago** [comment]
So many errors.

I think it's not detecting all of them. SETTINGS_TERRAFORMING_HELP which I fix in my PR is still broken into 2 lines.

**Comment by BrokenRegistry** [comment]
Yes, some translators have made a big mess!
Well... Except for the keywords ending by _HELP... they are my contribution only.
SETTINGS_TERRAFORMING_HELP was fixed in my last release, and is correctly loaded.
The first tools I made was only validating the loaded keyword references, ignoring those that were orphaned.
I had to adapt the loading code to detect and fixe these splitted lines errors...

**Comment by frank-zago** [comment]
Ce bug est toujours présent.

Par exemple, faire une audience et offrir de l'aide, de manière répétée dans la même audience. Des fois, on a le texte "Que voulez-vous donner ?" et des fois c'est "What do you want to give?". Les 2 correspondent à DIPLO_OFFER_AID_MENU_01. La réponse d'acceptation sera aussi tantôt en anglais, tantôt en Français.

**Comment by BrokenRegistry** [comment]
Oh! I think I found the bug location...
I'm working on it!

**Comment by BrokenRegistry** [comment]
Fixed.
These numbered keywords have their number removed and are added to a list of possible messages... So the English text has not been overwritten by the new one.
