### ISSUE TITLE
Hardcoded strings need to move inside text files

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#59]
These strings appear and should be in text files instead. For instance "Psilon Republic" will appear in some messages in French.

    // Customized nominal names
    ParamSpeciesName altairi    = new ParamSpeciesName(NAME_UI, "RACE_ALKARI",   "Alkari Sovereignty, Alkari, Alkaris");
    ParamSpeciesName ursinathi  = new ParamSpeciesName(NAME_UI, "RACE_BULRATHI", "Bulrathi Empire, Bulrathi, Bulrathis");
    ParamSpeciesName nazlok     = new ParamSpeciesName(NAME_UI, "RACE_DARLOK",   "Darloks, Darlok, Darloks");
    ParamSpeciesName human      = new ParamSpeciesName(NAME_UI, "RACE_HUMAN",    "Human Triumvirate, Human, Humans");
    ParamSpeciesName kholdan    = new ParamSpeciesName(NAME_UI, "RACE_KLACKON",  "Klackon Hive, Klackon, Klackons");
    ParamSpeciesName meklonar   = new ParamSpeciesName(NAME_UI, "RACE_MEKLAR",   "Meklar Dominion, Meklar, Meklars");
    ParamSpeciesName fiershan   = new ParamSpeciesName(NAME_UI, "RACE_MRRSHAN",  "Mrrshan Clan, Mrrshan, Mrrshan");
    ParamSpeciesName mentaran   = new ParamSpeciesName(NAME_UI, "RACE_PSILON",   "Psilon Republic, Psilon, Psilons");
    ParamSpeciesName ssslaura   = new ParamSpeciesName(NAME_UI, "RACE_SAKKRA",   "Sakkra Conclave, Sakkra, Sakkras");
    ParamSpeciesName cryslonoid = new ParamSpeciesName(NAME_UI, "RACE_SILICOID", "Silicoid Imperium, Silicoid, Silicoids");

**Comment by BrokenRegistry** [comment]
Custom base species nominal name option is now reserved for English language use only.
 (As other languages may use different or more keywords.)
