### ISSUE TITLE
Game title on screen is not centred on resizing

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#63]
If the game starts in a certain size and then goes fullscreen, "REMNANTS of the PRECURSORS" will stay at the same position, while the res on the menu ("Continue game", "New game", ...) is properly repositionned to the center. Changing the language to something then back will reposition the game title to its correct place.

**Comment by BrokenRegistry** [comment]
If you go "Fullscreen" the game should ask you to restart... This even if you change the language setting!
Can you, Please, give a more detailled sequence of action?

**Comment by BrokenRegistry** [comment]
The operating system is clearly informed that the windows must not be resized.
Using a tools that ignore this information is the problem!
Nothing can be done on the application level!
