### ISSUE TITLE
Similar races are called the same

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#65]
New bug from yesterday. All human races are "Humain", all Sakkra races are "Sakkra", ...
Easily seen in Council vote.

**Comment by BrokenRegistry** [comment]
Oops! When fixing the player race name not being updated by the options, I accidentally removed all the alternative race name...
-> Fixed All race name being the same when "Base Species Nominal Names" option was set.

**Comment by BrokenRegistry** [comment]
Closed
