### ISSUE TITLE
message nonsubstitué

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#67]
player_race_pluraladjec n'est pas substitué en jouant avec les Jack-Trade.

TECH_DISCOVERY_TITLE              | Les scientifiques [player_race_pluraladjec] réalisent une percée %1

Je suppose que la version anglaise aurait du être utilisée, mais ce n'est pas le cas.

**Comment by frank-zago** [comment]
Pareil pour celui-ci:
COUNCIL_SKIP_TO_PLAYER            | Passer au vote [player_raceadjec]

**Comment by BrokenRegistry** [comment]
Yes, unfortunately the 6 species added by Modnar only have English texts, using english [_keywords].
They need to be translated, or at least have their [_keywords] modified.
There is an option to hide these species, and another to remove them from the list of randomized opponents.
It's best not to use them in a foreign language.
I'll leave this issue open, in case anyone wants to start the translation work!

**Comment by BrokenRegistry** [comment]
Added an auto conversion of dialogue keywords for untranslated texts.
Far to be perfect, but better than [_MISSING_KEYWORD]
A true translation is still required!
Note: Some "Game Over" text are still missing for the 6 Modnar species (even in english!)... Artistic contribution will be apreciated.

**Comment by BrokenRegistry** [comment]
As I'm not going to edit all these dialogues, and the minimal fix has been released, I Close this issue.

**Comment by frank-zago** [comment]
/**
         * Companion world Greek letter prefix
         */
        public static final String[] compSysName = new String[]{"α", "β", "γ", "δ", "ε", "ζ"};// BR : added two possibilities

**Comment by BrokenRegistry** [comment]
Yep! I even added two of them... But since it's not a choice of the original author, I will not permanently change the font he chose for this interface... The fix still works fine, for every language.
