### ISSUE TITLE
All research at 100% but not really

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#68]
All 6 research boxes in bottom left indicate 100%.
To reproduce: start a new game, set research bar from main planet to max, next turn. After choosing all 6 techs to research, all indicators will be at 100%.

**Comment by frank-zago** [comment]
Indicators stay at 100% between turns, until the research in completed or the Tech panel accessed.

**Comment by BrokenRegistry** [comment]
Fixed.
The Governor was not always updating this informantion...
