### ISSUE TITLE
possibly unconnected hotkeys in Empire panel

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#71]
These hotkeys belong to the Empire panel.

    RACES_HELP_HK        | →HK_HEADER← →HK_F1← <br><br>Arrows Down/Up : Next/Previous Empire. →HK_TAB←<br><br>A : Select Embassy Panel.<br>D : Select Diplomat Panel.<br>S : Select Spies Panel. <br>→HK_ESCAPE←

However only ESC, A and the arrows appear to work. D and S do nothing AFAICS.

**Comment by BrokenRegistry** [comment]
Improved Empire Hotkey description.
D and S are only active when the player's empire is selected.
A is only active when an opponent is selected.

**Comment by frank-zago** [comment]
I see. That only works in the Diplomat sub-panel though. S & D should work everywhere. At least S should work in the Spy subpanel.
