### ISSUE TITLE
Hardcoded "Free" string in code

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#72]
The tech panel shows "Free" in the background for the free tech level.

    src/rotp/ui/tech/AllocateTechUI.java:        String numStr = tierNum==0? "Free" : str(tierNum);

This should be translatable.

**Comment by BrokenRegistry** [comment]
Oops! I forgot to move this one to Label.txt
Fixed

**Comment by frank-zago** [comment]
I see. That only works in the Diplomat sub-panel though. S & D should work everywhere. At least S should work in the Spy subpanel.
