### ISSUE TITLE
? should always work as a hotkey like F1 (or not work at all)

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#74]
It's a bit inconsistent. '?' is equivalent to F1 to show the help in the System / Fleet / Designs tabs, but not in Empires / Colonies / Tech tabs. It also not documented as such in these tabs.

**Comment by BrokenRegistry** [comment]
"F1" is the standard way to call help.
I don't know why "?" was used too, as it's non standard and do not work with all keyboards...
I will not remove it, as some player may be used to it, but it's no more listed in the hotkey list.
