### ISSUE TITLE
Nom de planète incomplet dans un message

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#75]
Si "α Psilar" se rebelle, le α n'est pas affiché et il y a une espace à la place. Le nom est correct sur la carte de la galaxie. Sûrement un problème d'encoding.

    GNN_PLAYER_REBELLION              | %1 s'est rebellé et refuse de contribuer à [rebelling_empire]. Au moins %2 millions de rebelles contrôlent la colonie. Des troupes doivent être envoyées pour réprimer le soulèvement.

**Comment by BrokenRegistry** [comment]
Do you have a save before the rebellion? It would help to debug this one.

**Comment by frank-zago** [comment]
Sorry, I don't.

**Comment by BrokenRegistry** [comment]
The GNN font do not have the Greek characted set!
I changed the font for the French language (Many languages uses different fonts)
I'll ask the community before changing the font in English... Because it would change the overall aesthetic and no one seems to have noticed this bug!

**Comment by BrokenRegistry** [comment]
After looking at the species system name: None of them includes Greek characters!
So this was not a bug, just a no-feature!
  --> Restored Original font. Wich will only be replaced dynamically, when the original GNN font will not be able to display the system name.

**Comment by frank-zago** [comment]
Greek letters are used when starting with companion planets.
