### ISSUE TITLE
incorrect or confusing battle result

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#79]
This is another long standing minor bug. After a battle, each stack of the beaten fleet is either marked as "RETREATED" or "DESTROYED".
Sometimes a stack with 0 ships left is marked as "RETREATED", not "DESTROYED".

**Comment by BrokenRegistry** [comment]
It is still a mystery why the boolean "Retreated" is set to true when there are no ships left.
Anyway, a correct result will now be displayed.
