### ISSUE TITLE
New governor headshot in button is always Psilon

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#82]
I'd have expected the headshot to be that of the player's race.

**Comment by frank-zago** [comment]
It's actually the headshot of whatever species was played in the first game. 
If a new game is started, the headshot is not refreshed.

**Comment by BrokenRegistry** [comment]
Oh! Right. It updates when loading an old game, but not on a new start!

**Comment by BrokenRegistry** [comment]
Fixed, the icon updates now on start and restart too.
