### ISSUE TITLE
Possibly hardcoded string in planet info

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#83]
When colonizing (or taking) a planet with existing factories, their numbers is indicated in the planet info in the top right. 
For instance: "60 Mechanar Usines". This message appears harcoded somewhere. It should be "60 Usines Mechanariennes"

**Comment by BrokenRegistry** [comment]
Yes, this was a mod addition, and adding reference to language token (races specific) would require the label to be mandatory translated in every language... [alien_race] -> [alien_race_pluraladjecF]
But the little fix I made for the 6 added races remove this requirement.
So, captured Alien Factory Display have now their dedicated label.
