### ISSUE TITLE
"Default Value" is not translatable

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#90]
2 of them appear in the Options tab.

src/rotp/ui/util/IParam.java:       String help = labelFormat("Default Value") + guideDefaultValue();
src/rotp/ui/util/IParam.java:           help += htmlTuneFont(-2, "&emsp<i>(set with Middle Click)<i/>");

There are more hardcoded strings in that file.

**Comment by BrokenRegistry** [comment]
Yes, I guess it's time I finalise the "Guide"...

**Comment by BrokenRegistry** [comment]
Done
