### ISSUE TITLE
StarGate doesn't build when selected

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#91]
Select a planet to build a stargate, set the quantity to 1. Nothing happens.
To build it I have to move the slider. Furthermore, the slider doesn't adjust to just what is needed to finish the stargate like it does for ships; the remainder goes to tech or the treasury.

**Comment by BrokenRegistry** [comment]
StarGates do not follow the ship rules and methods... Quantity does nothing! and ship cost prediction do not apply.
I'll see if I can improve a bit the automation.

**Comment by BrokenRegistry** [comment]
No Bug!
The governor appropriately reallocates the surplus when it takes less than a year to complete the Stargate construction.
If the governor is enabled and you manually select the Stargate, use SmartMax (click on the text on the right) to automatically adjust the slider.
If the governor is disabled, it is up to you to adjust the allocations, SmartMax is here to help.
If this is not what is happening in your game, please share it and I will investigate.

**Comment by BrokenRegistry** [comment]
Closed, bot a bug
