### ISSUE TITLE
colony view not refreshed when using F7 + mouse hover

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#92]
to reproduce (need at least 2 planets being attacked): 
- press F7 for a planet being attacked.
- move the mouse cursor over it
- press F7 again to go the next attacked planet
--> the colony right panel still  displays the previous planet.

This doesn't happen with F2/F3.

**Comment by frank-zago** [comment]
Same issue with F5/F6

**Comment by BrokenRegistry** [comment]
Fixed
