### ISSUE TITLE
We're at war but can we make an alliance, or do business?

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#94]
So often diplomacy gets weird, with a race visiting to declare war, then in the same turn asking to increase trade or declaring war on another race. 

I've even seen race A visiting to ask to declare war on race B, which I agreed to, then race B visiting (with the at war status) asking for an alliance. Final status is that I'm now allied to race B with a recalled ambassador.

I think a first step to fix all that would be to intermediately recall the ambassadors when war is declared (which may be the case already), but also go through whatever queue is holding these events and remove specific visits.

**Comment by BrokenRegistry** [comment]
I will not play in AI (Xilmi Private Domains)... These inconsistencies can be seen as ministries not talking to each other...
Some time ago, I already fixed the trade offers displayed after a declaration of war by automatically refusing them.
The effects of trade offers displayed before a declaration of war should be canceled once the war is activated.
Accepting the alliance should stop the war and restore the ambassador... I will check that.

**Comment by BrokenRegistry** [comment]
Although it is quite strange to accept an alliance the same turn that the war was accepted... but why not?!
A messenger was sent, and it's up to the player to decide to change side or not!
Alliance treaty was already stopping the war, but not restoring ambassadors, as normally they should not be gone!
Logic then dictates the return of the ambassadors...
Done.
