### ISSUE TITLE
split tech stealing

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#96]
"tech stealing" is covering both spying and technology plunder after taking a planet. I think these should be separate options, with plunder being a numerical option (set to 6, which is the current default).

**Comment by BrokenRegistry** [comment]
New Max Techs capture option when invading a colony, which is independent of the tech stealing option.
  - If technology theft was previously prohibited, then maximum number of technologies captured = 0.
