### ISSUE TITLE
Hotkeys to browse Idle fleet doesn't work

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#97]
From MAIN_HELP_HK:  "... Space/Page Down/Page Up : Next/Previous player Idle fleet ..." 
None of these keys appear to do anything, although there are idle fleets.

**Comment by BrokenRegistry** [comment]
Works perfectly well on my computer!
What is your keyboard layout? Page Down/Page Up could be a problem, but space should not!
Can you send me a problematic saved game?

**Comment by BrokenRegistry** [comment]
All ships have been given orders.
Those in orbit are either in auto-scout or auto-colony mode, waiting for a planet to explore or colonize...

New feature:
- Loop thru Idle fleets: "Shift-" = Auto but still idle.

**Comment by frank-zago** [comment]
Fair enough.
