### ISSUE TITLE
loading a new file will automatically erase '!!! To Replay Last Turn !!!.rotp'

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#99]
Just the action of starting rotp, loading a previous game will immediately save it under '!!! To Replay Last Turn !!!.rotp'. I'm not sure that's a desirable behavior. Waiting for the next turn might be more sensible.

**Comment by BrokenRegistry** [comment]
It was a bug. Fixed

**Comment by BrokenRegistry** [comment]
Also Fixed the fix... Wich was sometime leading to a wrong warning on load.
